### ISSUE TITLE
Why is core::ops::range not used ?

### ISSUE THREAD

**Issue by planetoryd** [ripytide/discrete_range_map#45]
There is a custom impl of InclusiveInterval. And the traits are not impled for `core::ops::range`. The syntax is really ugly. Why ?

**Comment by ripytide** [comment]
It's not `Copy` which we require currently. We used to just require `Clone` but the code was _much_ harder to maintain with all the `.clone()`s everywhere. And realistically, most use-cases have `I: Copy` anyway.
