### ISSUE TITLE
Don't publicly expose test_ranges.rs

### ISSUE THREAD

**Issue by stefnotch** [ripytide/discrete_range_map#49]
It's possible to access the functions from https://github.com/ripytide/discrete_range_map/blob/408f4e020ebdb984b752b00fc1b8a9ef604909f7/src/test_ranges.rs#L20
They also show up in the [documentation](https://docs.rs/discrete_range_map/latest/discrete_range_map/test_ranges/fn.uu.html). Ideally, those would either 
- be internal and inaccessible
- or be generic, with maybe slightly longer names and publicly exposed

**Comment by ripytide** [comment]
Good point, I wonder which option to go for, I guess it would provide an easier way to get started with the library if you didn't have to create your own range type if they were public+generic.

**Comment by stefnotch** [comment]
The library does have one range type, which is the `InclusiveInterval;`. It just neither has a constructor, nor a nice and short way of constructing it.
So to construct it, one has to do `InclusiveInterval { start: 42, end: 69 }`.

(On that note, it slightly surprised me that there isn't an `ExclusiveInterval`?)

**Comment by ripytide** [comment]
The point on there not being an `ExclusiveInterval` is that because we enforce `Finite` + `Discrete` on our point datatype we can *always* convert a valid range from Exclusive-Exclusive to Inclusive-Inclusive which makes everything simpler.

**Comment by ripytide** [comment]
Yeah I think the best way may be to make the constructors used in all the doc-tests simple generic helpers to create the `InclusiveInterval`, I'll do that
