### ISSUE TITLE
From Range and back

### ISSUE THREAD

**Issue by stefnotch** [ripytide/discrete_range_map#50]
It'd be lovely to be able to to turn one of the rather unwieldy Rust `RangeInclusive`s into a `InclusiveInterval` and back.

I'm more than happy to create a PR for this if desired.

**Comment by ripytide** [comment]
Do you mean just adding `impl From<RangeInclusive> for InclusiveInterval` and `impl From<InclusiveInterval> for RangeInclusive`? If so then I am happy to add this.

**Comment by stefnotch** [comment]
Yes, exactly

**Comment by ripytide** [comment]
I added `core::ops::Range` as well while I was at it
