### ISSUE TITLE
insert_overwrite should return results from cut

### ISSUE THREAD

**Issue by stefnotch** [ripytide/discrete_range_map#51]
I would have expected `insert_overwrite` to return an iterator over the old items, since most other insert methods return the old values or something.

Judging from the source code, it'd be a quick tweak.
https://docs.rs/discrete_range_map/latest/src/discrete_range_map/discrete_range_map.rs.html#1232-1240

**Comment by ripytide** [comment]
Good point, I didn't need this in my use-case, but that would match up with the `BTreeMap`'s `insert`. The other `insert_*` methods are are bit trickier in this regard so might require a bit more work.
