### ISSUE TITLE
Explain merging

### ISSUE THREAD

**Issue by stefnotch** [ripytide/discrete_range_map#52]
I was looking at the https://docs.rs/discrete_range_map/latest/discrete_range_map/discrete_range_map/struct.DiscreteRangeMap.html#method.insert_merge_overlapping functions, and realised that I had no clue what `merge` exactly means. Does it merge stuff if it's equal? Does it do more than that? Is there a way of customising it, or would that be nonsense?

Ideally, that documentation would link to
https://docs.rs/discrete_range_map/latest/discrete_range_map/index.html#merging
and that section would be slightly expanded.

**Comment by ripytide** [comment]
Good point, alternatively we could just remove the `merging` section from the top-level documentation as all the required information you asked about should already be available in the method docs on each method already.

**Comment by ripytide** [comment]
I'm not sure what you mean by customizing the merging, the method should be fully unambiguous from the methods documentation, perhaps `insert_merge_touching_if_values_equal`?

**Comment by stefnotch** [comment]
Ah, I see. I somehow missed the "The value of the merged-together range is set to the value given for this insertion." line, that's embarrassing. 

Well, I suppose that answers my questions.

**Comment by stefnotch** [comment]
I'll leave this issue open so that updating `insert_merge_touching_if_values_equal` and the top level `merging` sections won't be forgotten about.

If you want some text for the top level section, may I suggest
> When a range "merges" other ranges it absorbs them to become larger. This means completely replacing the value of the other ranges with the new value.

Also, to partially explain my initial confusion: Before looking at this library, I looked at `rangemap`. It has a "coalescing" feature, which is what I initially thought of when I read "merging".
https://docs.rs/rangemap/latest/rangemap/map/struct.RangeMap.html#method.insert

**Comment by ripytide** [comment]
I think I'll add some more examples to the merging methods with demonstrate the merging and call this issue fixed. I've removed the merging section from the readme as it doesn't really belong there.
