### ISSUE TITLE
Impl DiscreteFinite for usize

### ISSUE THREAD

**Issue by stefnotch** [ripytide/discrete_range_map#54]
Would it be possible to implement DiscreteFinite for usize?

https://github.com/ripytide/discrete_range_map/blob/main/src/discrete_finite.rs

 I have a use case where I'm using array indices as the keys for a range map. The rough idea is that most of the time, the array has mostly the same values, so storing it as a range map is far more efficient (and makes a few algorithms easier to implement). Hence this request.

**Comment by ripytide** [comment]
Absolutely, I completely forget about `usize` whoops.

I think given all the brilliant suggestions you've provided thus far, I will try to implement them all in the next few days and then after a bit of testing releasing all the new improvements in a `v0.7.0`.
